#!/bin/bash

#Save and process degree distributions from
#A. D. Broido and A. Clauset, Scale-free networks are rare, Nature Communications 10 (2019), 1–10.
git clone https://github.com/adbroido/SFAnalysis
python3 estimate_N.py --h=3 `ls ./SFAnalysis/degreesequences/*.txt | grep -v -e "directedin\|directedout"` > results/broido_clauset_3.txt
python3 estimate_N.py --h=4 `ls ./SFAnalysis/degreesequences/*.txt | grep -v -e "directedin\|directedout"` > results/broido_clauset_4.txt
python3 estimate_N.py --h=5 `ls ./SFAnalysis/degreesequences/*.txt | grep -v -e "directedin\|directedout"` > results/broido_clauset_5.txt


#Save degree information from 
#D. M. Feehan and A. S. Mahmud, Quantifying population contact patterns in the United States during the COVID-19 pandemic, Nature Communications 12 (2021), 1–9. 
git clone https://github.com/dfeehan/bics-paper-release.git
cd ./bics-paper-release/bics-paper-code/code/
R -e "install.packages('piggyback', 'data.table')"
#you actually need the download part to work
Rscript bics-paper-release/bics-paper-code/code/00-run-all.R || true
#"adjusted" versions are the distributions adjusted for USA population by Feehan and Mahmud
Rscript bics_save_waves.R

#wave 0 is excluded because the surveys had a cut off at degree 10
python3 estimate_N.py --h=3 --n=330000000 COVID19-Wave[1-3]*.csv > results/feehan_mahmud_3.txt
python3 estimate_N.py --h=4 --n=330000000 COVID19-Wave[1-3]*.csv > results/feehan_mahmud_4.txt
python3 estimate_N.py --h=5 --n=330000000 COVID19-Wave[1-3]*.csv > results/feehan_mahmud_5.txt
#For estimating, for example, emb(P_4, G) or emb(P_5, G) we need at least i_T=2
python3 estimate_N.py --h=4 --i_T=2 --n=330000000 COVID19-Wave[1-3]*.csv > results/feehan_mahmud_4_i_T_2.txt
python3 estimate_N.py --h=5 --i_T=2 --n=330000000 COVID19-Wave[1-3]*.csv > results/feehan_mahmud_5_i_T_2.txt

