#!/bin/bash

#Save and process degree distributions from
#A. D. Broido and A. Clauset, Scale-free networks are rare, Nature Communications 10 (2019), 1–10.
git clone https://github.com/adbroido/SFAnalysis
python3 estimate_N.py --h=3 --min_n=10000 `ls ./SFAnalysis/degreesequences/*.txt | grep -v -e "directedin\|directedout"` > results/broido_clauset_3.txt
python3 estimate_N.py --h=4 --min_n=10000 `ls ./SFAnalysis/degreesequences/*.txt | grep -v -e "directedin\|directedout"` > results/broido_clauset_4.txt
python3 estimate_N.py --h=5 --min_n=10000 `ls ./SFAnalysis/degreesequences/*.txt | grep -v -e "directedin\|directedout"` > results/broido_clauset_5.txt

#Save degree information from 
#D. M. Feehan and A. S. Mahmud, Quantifying population contact patterns in the United States during the COVID-19 pandemic, Nature Communications 12 (2021), 1–9. 
git clone https://github.com/dfeehan/bics-paper-release.git
R -e "install.packages(c('piggyback', 'data.table'))"
#we actually only need the download part to work
Rscript bics-paper-release/bics-paper-code/code/00-run-all.R || true
#"adjusted" versions are the distributions adjusted for USA population by Feehan and Mahmud
Rscript bics_save_waves.R

#wave 0 is excluded because the surveys had a cut off at degree 10
python3 estimate_N.py --h=3 --n=330000000 COVID19-Wave*[1-3]*.csv > results/feehan_mahmud_3.txt
python3 estimate_N.py --h=4 --n=330000000 COVID19-Wave*[1-3]*.csv > results/feehan_mahmud_4.txt
python3 estimate_N.py --h=5 --n=330000000 COVID19-Wave*[1-3]*.csv > results/feehan_mahmud_5.txt
#for emb(P_4, G) or similar
python3 estimate_N.py --h=4 --i_T=2 --n=330000000 COVID19-Wave*[1-3]*.csv > results/feehan_mahmud_4_i_T_2.txt
#for emb(P_5, G) or similar 
python3 estimate_N.py --h=5 --i_T=3 --n=330000000 COVID19-Wave*[1-3]*.csv > results/feehan_mahmud_5_i_T_3.txt
#if we were able to sample a random edge (Theorem 6, |V(O)|=2)
python3 estimate_N.py --h=3 --n=330000000 --O_size=2 COVID19-Wave*[1-3]*.csv > results/feehan_mahmud_3_O_2.txt

echo "Done!"
